.TH "EILEAN-CONFIGURATION\&.NIX" "5" "01/01/1980" "Home Manager"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.SH "NAME"
\fIeilean\-configuration\&.nix\fP \- Eilean configuration specification
.SH "DESCRIPTION"
.sp
Self-host your own digital island.
.sp
Eilean extends the NixOS module system with the following options.
.sp
.SH "OPTIONS"
.PP
